Rspec/test_like_a_hero/config/routes.rb
Rails.application.routes.draw do
  resources :enemies, only: [:index, :new, :create, :update, :destroy, :show]
  resources :users, only: [:index, :create]
  resources :weapons, only: [:index, :new, :create, :destroy, :show]
  root to: "weapons#index"
end

Rspec/test_like_a_hero/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

Rspec/test_like_a_hero/app/models/enemy.rb
class Enemy < ApplicationRecord
    enum kind: [ :goblin, :orc, :demon, :dragon ]
    validates :level, numericality: { greater_than: 0, less_than_or_equal_to: 99 }
    validates_presence_of :name, :power_base, :power_step, :level, :kind

    def current_power
        power_base + ((level - 1) * power_step)
    end

    def title
        "#{self.name} ##{self.level}"
    end
end

Rspec/test_like_a_hero/app/models/user.rb
class User < ApplicationRecord
    enum kind: [ :knight, :wizard ]

    validates :level, numericality: { greter_than: 0, less_than_or_equal_to: 99 }

    def title
        "#{self.kind} #{self.nickname} ##{self.level}"
    end
end

Rspec/test_like_a_hero/app/models/weapon.rb
class Weapon < ApplicationRecord
    validates :name, presence: true

    def title
        "#{self.name} ##{self.level}"
    end

    def current_power
        (power_base + ((level - 1) * power_step))
    end
end

Rspec/test_like_a_hero/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

Rspec/test_like_a_hero/app/controllers/enemies_controller.rb
class EnemiesController < ApplicationController
  before_action :set_enemy

  def index
    @enemies = Enemy.order(name: :asc)
  end

  def show
    @enemy = set_enemy
  end

  def new
    @enemy = Enemy.new
  end

  def create
    @enemy = Enemy.create(enemy_params)
    redirect_to enemies_path
  end

  def update
    if @enemy.present? 
      if @enemy.update(enemy_params)
        render json: @enemy, status: :ok
      else
        render json: { errors: @enemy.errors }, status: :unprocessable_entity
      end
    else
      render json: { message: "Couldn't find Enemy" }, status: :not_found
    end
  end

  def destroy
    if @enemy.present?
      @enemy.destroy
      #redirect_to enemies_path
      render json: { message: "Enemy deleted successfully" }, status: :no_content
    else
      render json: { message: "Couldn't find Enemy" }, status: :not_found
    end
  end


  private

  def enemy_params
    params.require(:enemy).permit(:name, :power_base, :power_step, :level, :kind)
  end

  def set_enemy
    @enemy = Enemy.where(id: params[:id]).first
  rescue ActiveRecord::RecordNotFound => e
    render json: { message: e.message }, status: :not_found
  end
end

Rspec/test_like_a_hero/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def create
    @user = User.create(user_params)
    redirect_to users_path
  end


  private

  def user_params
    params.require(:user).permit(:nickname, :kind, :level)
  end
end

Rspec/test_like_a_hero/app/controllers/weapons_controller.rb
class WeaponsController < ApplicationController
    
    def index
        @weapons = Weapon.order(name: :asc)
    end

    def create
        @weapon = Weapon.create(weapon_params)
        redirect_to weapons_path
    end

    def destroy
        weapon = set_weapon
        weapon.destroy
        redirect_to root_path
    end

    def destroy
        if @weapon.present?
          @weapon.destroy
          #redirect_to enemies_path
          render json: { message: "Weapon deleted successfully" }, status: :no_content
        else
          render json: { message: "Couldn't find Weapon" }, status: :not_found
        end
      end

    def show
        @weapon = set_weapon
    end

    def new
        @weapon = Weapon.new
    end

    private

    def weapon_params
        params.require(:weapon).permit(:name, :description, :power_base, :power_step, :level)
    end

    def set_weapon
        @weapon = Weapon.where(id: params[:id]).first
    end
end

Rspec/test_like_a_hero/app/helpers/application_helper.rb
module ApplicationHelper
end

Rspec/test_like_a_hero/app/views/enemies/destroy.html.erb
<h1>Enemies#destroy</h1>
<p>Find me in app/views/enemies/destroy.html.erb</p>

Rspec/test_like_a_hero/app/views/enemies/index.html.erb
<% @enemies.each do |enemy| %>
    <h3><%= enemy.title %></h3>
    Poder: <%= enemy.current_power %>
    <h3><%= link_to "Detalhes", enemy %>
    <hr>
<% end %>

Rspec/test_like_a_hero/app/views/enemies/new.html.erb
<p><h3>Criar novo inimigo</h3></p>
<%= form_for @enemy do |form| %>

    <div>
        <%= form.label :name %>
        <br>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :level %>
        <br>
        <%= form.number_field :level %>
    </div>

    <div>
        <%= form.label :power_base %>
        <br>
        <%= form.number_field :power_base %>
    </div>
    
    <div>
        <%= form.label :power_step %>
        <br>
        <%= form.number_field :power_step %>
    </div>

    <div>
        <%= form.label :kind %>
        <br>
        <select name="enemy[kind]">
            <option value='goblin'>Goblin</option>
            <option value='orc'>Orc</option>
            <option value='demon'>Demon</option>
            <option value='dragon'>Dragon</option>
        </select>
    </div>

    <%= form.submit "Criar" %>
<% end %>

Rspec/test_like_a_hero/app/views/enemies/show.html.erb
<h2><p><%= @enemy.title %></p></h2>
<p>Poder: <%= @enemy.current_power %></p>
<p>Poder base: <%= @enemy.power_base %></p>
<p>Passo de poder: <%= @enemy.power_step %></p>
<%= link_to 'Deletar', @enemy, method: :delete, data: { confirm: "Tem certeza que deseja remover #{@enemy.name}?" } %>
<hr>

Rspec/test_like_a_hero/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestLikeAHero</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <h2><%= link_to "FerroStore", root_url %></h2>
  <h2><%= link_to "Artigos para caçadores", enemies_path %></h2>
  <%= link_to "nova arma FERRO", new_weapon_path %>
  <%= link_to "novo monstro FERRO", new_enemy_path %>
  <br><br>

  <body>
    <%= yield %>
  </body>
</html>

Rspec/test_like_a_hero/app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

Rspec/test_like_a_hero/app/views/users/index.html.erb
<% @users.each do |user| %>
    <p><%= user.title %></p>
<% end %>

Rspec/test_like_a_hero/app/views/weapons/index.html.erb
<% @weapons.each do |weapon| %>
    <h3><%= weapon.title %></h3>
    Poder: <%= weapon.current_power %>
    <h3><%= link_to "Detalhes", weapon %>
    <hr>
<% end %>

Rspec/test_like_a_hero/app/views/weapons/new.html.erb
<p><h3>Criar nova arma</h3></p>
<%= form_for @weapon do |form| %>

    <div>
        <%= form.label :name %>
        <br>
        <%= form.text_field :name %>
    </div>

    <div>
        <%= form.label :description %>
        <br>
        <%= form.text_area :description %>
    </div>

    <div>
        <%= form.label :level %>
        <br>
        <%= form.number_field :level %>
    </div>

    <div>
        <%= form.label :power_base %>
        <br>
        <%= form.number_field :power_base %>
    </div>
    
    <div>
        <%= form.label :power_step %>
        <br>
        <%= form.number_field :power_step %>
    </div>

    <%= form.submit "Criar" %>
<% end %>

Rspec/test_like_a_hero/app/views/weapons/show.html.erb
<h2><p><%= @weapon.title %></p></h2>
<p><%= @weapon.description %></p>
<p>Poder: <%= @weapon.current_power %></p>
<p>Poder base: <%= @weapon.power_base %></p>
<p>Passo de poder: <%= @weapon.power_step %></p>
<%= link_to 'Deletar', @weapon, method: :delete, data: { confirm: "Tem certeza que deseja remover #{@weapon.name}?" } %>
<hr>